# Generated by Django 4.1.2 on 2022-11-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='Leave_date',
        ),
    ]
