# Generated by Django 4.1.2 on 2022-11-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_experience_leave_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='Leave_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='applied_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
