# Generated by Django 4.1.2 on 2022-11-25 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobs_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='applicant',
        ),
        migrations.AddField(
            model_name='jobs',
            name='applicant',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobseeker', to=settings.AUTH_USER_MODEL),
        ),
    ]
