# Generated by Django 4.1.2 on 2022-11-26 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_jobs_applicant_jobs_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='number_of_appicants',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='applicant',
            field=models.ManyToManyField(blank=True, related_name='jobseeker', to=settings.AUTH_USER_MODEL),
        ),
    ]
