# Generated by Django 4.1.2 on 2022-11-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_jobs_number_of_appicants_alter_jobs_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='number_of_reports',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='number_of_appicants',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
