# Generated by Django 4.1.2 on 2022-12-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='compnay_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='reports',
            field=models.IntegerField(null=True),
        ),
    ]
