# Generated by Django 4.1.2 on 2022-12-02 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_compnay_name_account_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='compnay_name',
        ),
        migrations.AlterField(
            model_name='account',
            name='reports',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compnany_name', models.CharField(max_length=500, null=True)),
                ('objective', models.CharField(max_length=500, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
