# Generated by Django 4.1.2 on 2022-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_account_compnay_name_alter_account_reports_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='objective',
            new_name='location',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vision',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
