# Generated by Django 4.1.2 on 2022-12-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_objective_companyprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
