# Generated by Django 4.1.2 on 2022-12-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_companyprofile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='number',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
