# Generated by Django 4.1.2 on 2022-12-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_companyprofile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Company',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='accounts.companyprofile'),
        ),
    ]
