# Generated by Django 4.1.2 on 2022-12-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_jobs_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='compnany_name',
            new_name='company_name',
        ),
    ]
