# Generated by Django 4.1.2 on 2022-12-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_notification_user_notification_notified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thread_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
