# Generated by Django 4.1.2 on 2022-12-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_notification_notified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
