# Generated by Django 4.1.2 on 2022-12-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
